# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "singpass-form-my-own-store"
client_id = "a49c5ced1256443bf410c09a2d041747"
application_url = "https://surround-explicit-reader-hearts.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://surround-explicit-reader-hearts.trycloudflare.com/auth/callback",
  "https://surround-explicit-reader-hearts.trycloudflare.com/auth/shopify/callback",
  "https://surround-explicit-reader-hearts.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-singpass-custom-form.myshopify.com"
